name: Package and release
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Package
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        uses: BigWigsMods/packager@v2
      - name: Package and release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
